// Code generated by protoc-gen-go.
// source: contentservice.proto
// DO NOT EDIT!

/*
Package contentservice is a generated protocol buffer package.

It is generated from these files:
	contentservice.proto

It has these top-level messages:
	Params
	Request
	Result
	InspiPutResponse
	VendorWebPutResponse
	Error
	Response
*/
package contentservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// File params sent as part of put request
type Params struct {
	Contracttorid int64  `protobuf:"varint,1,opt,name=contracttorid" json:"contracttorid,omitempty"`
	Ordernumber   int64  `protobuf:"varint,2,opt,name=ordernumber" json:"ordernumber,omitempty"`
	Imagetype     int32  `protobuf:"varint,3,opt,name=imagetype" json:"imagetype,omitempty"`
	Filename      string `protobuf:"bytes,4,opt,name=filename" json:"filename,omitempty"`
	Imagewidth    int32  `protobuf:"varint,5,opt,name=imagewidth" json:"imagewidth,omitempty"`
	Imageheight   int32  `protobuf:"varint,6,opt,name=imageheight" json:"imageheight,omitempty"`
	Releasedate   string `protobuf:"bytes,7,opt,name=releasedate" json:"releasedate,omitempty"`
	Deptcode      string `protobuf:"bytes,8,opt,name=deptcode" json:"deptcode,omitempty"`
	Filecontents  []byte `protobuf:"bytes,9,opt,name=filecontents,proto3" json:"filecontents,omitempty"`
}

func (m *Params) Reset()                    { *m = Params{} }
func (m *Params) String() string            { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()               {}
func (*Params) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Params) GetContracttorid() int64 {
	if m != nil {
		return m.Contracttorid
	}
	return 0
}

func (m *Params) GetOrdernumber() int64 {
	if m != nil {
		return m.Ordernumber
	}
	return 0
}

func (m *Params) GetImagetype() int32 {
	if m != nil {
		return m.Imagetype
	}
	return 0
}

func (m *Params) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Params) GetImagewidth() int32 {
	if m != nil {
		return m.Imagewidth
	}
	return 0
}

func (m *Params) GetImageheight() int32 {
	if m != nil {
		return m.Imageheight
	}
	return 0
}

func (m *Params) GetReleasedate() string {
	if m != nil {
		return m.Releasedate
	}
	return ""
}

func (m *Params) GetDeptcode() string {
	if m != nil {
		return m.Deptcode
	}
	return ""
}

func (m *Params) GetFilecontents() []byte {
	if m != nil {
		return m.Filecontents
	}
	return nil
}

// Request sent to the Put call
type Request struct {
	Jsonrpc        string  `protobuf:"bytes,1,opt,name=jsonrpc" json:"jsonrpc,omitempty"`
	Method         string  `protobuf:"bytes,2,opt,name=method" json:"method,omitempty"`
	Params         *Params `protobuf:"bytes,3,opt,name=params" json:"params,omitempty"`
	Id             int32   `protobuf:"varint,4,opt,name=id" json:"id,omitempty"`
	Asyncmessageid int32   `protobuf:"varint,5,opt,name=asyncmessageid" json:"asyncmessageid,omitempty"`
	Traceid        int32   `protobuf:"varint,6,opt,name=traceid" json:"traceid,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetJsonrpc() string {
	if m != nil {
		return m.Jsonrpc
	}
	return ""
}

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Request) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetAsyncmessageid() int32 {
	if m != nil {
		return m.Asyncmessageid
	}
	return 0
}

func (m *Request) GetTraceid() int32 {
	if m != nil {
		return m.Traceid
	}
	return 0
}

// Message when Put request is successful
type Result struct {
	Contractorid          int32                 `protobuf:"varint,1,opt,name=contractorid" json:"contractorid,omitempty"`
	Releasedate           string                `protobuf:"bytes,2,opt,name=releasedate" json:"releasedate,omitempty"`
	Scandate              string                `protobuf:"bytes,3,opt,name=scandate" json:"scandate,omitempty"`
	Imagetype             int32                 `protobuf:"varint,4,opt,name=imagetype" json:"imagetype,omitempty"`
	Imagewidth            int32                 `protobuf:"varint,5,opt,name=imagewidth" json:"imagewidth,omitempty"`
	Imageheight           int32                 `protobuf:"varint,6,opt,name=imageheight" json:"imageheight,omitempty"`
	Deptcode              string                `protobuf:"bytes,7,opt,name=deptcode" json:"deptcode,omitempty"`
	Descprefix            string                `protobuf:"bytes,8,opt,name=descprefix" json:"descprefix,omitempty"`
	Desctext              string                `protobuf:"bytes,9,opt,name=desctext" json:"desctext,omitempty"`
	Category              string                `protobuf:"bytes,10,opt,name=category" json:"category,omitempty"`
	Ordernumber           int64                 `protobuf:"varint,11,opt,name=ordernumber" json:"ordernumber,omitempty"`
	Archived              string                `protobuf:"bytes,12,opt,name=archived" json:"archived,omitempty"`
	Datecreated           string                `protobuf:"bytes,13,opt,name=datecreated" json:"datecreated,omitempty"`
	Datemodefied          string                `protobuf:"bytes,14,opt,name=datemodefied" json:"datemodefied,omitempty"`
	Filesize              int32                 `protobuf:"varint,15,opt,name=filesize" json:"filesize,omitempty"`
	Id                    int32                 `protobuf:"varint,16,opt,name=id" json:"id,omitempty"`
	Imagefilename         string                `protobuf:"bytes,17,opt,name=imagefilename" json:"imagefilename,omitempty"`
	Imagerotated          int32                 `protobuf:"varint,18,opt,name=imagerotated" json:"imagerotated,omitempty"`
	Thumbnailsize         int32                 `protobuf:"varint,19,opt,name=thumbnailsize" json:"thumbnailsize,omitempty"`
	Webfilename           string                `protobuf:"bytes,20,opt,name=webfilename" json:"webfilename,omitempty"`
	Mimetype              string                `protobuf:"bytes,21,opt,name=mimetype" json:"mimetype,omitempty"`
	Inspiresponsedata     *InspiPutResponse     `protobuf:"bytes,22,opt,name=inspiresponsedata" json:"inspiresponsedata,omitempty"`
	Vendorwebresponsedata *VendorWebPutResponse `protobuf:"bytes,23,opt,name=vendorwebresponsedata" json:"vendorwebresponsedata,omitempty"`
	Guid                  string                `protobuf:"bytes,24,opt,name=guid" json:"guid,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Result) GetContractorid() int32 {
	if m != nil {
		return m.Contractorid
	}
	return 0
}

func (m *Result) GetReleasedate() string {
	if m != nil {
		return m.Releasedate
	}
	return ""
}

func (m *Result) GetScandate() string {
	if m != nil {
		return m.Scandate
	}
	return ""
}

func (m *Result) GetImagetype() int32 {
	if m != nil {
		return m.Imagetype
	}
	return 0
}

func (m *Result) GetImagewidth() int32 {
	if m != nil {
		return m.Imagewidth
	}
	return 0
}

func (m *Result) GetImageheight() int32 {
	if m != nil {
		return m.Imageheight
	}
	return 0
}

func (m *Result) GetDeptcode() string {
	if m != nil {
		return m.Deptcode
	}
	return ""
}

func (m *Result) GetDescprefix() string {
	if m != nil {
		return m.Descprefix
	}
	return ""
}

func (m *Result) GetDesctext() string {
	if m != nil {
		return m.Desctext
	}
	return ""
}

func (m *Result) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Result) GetOrdernumber() int64 {
	if m != nil {
		return m.Ordernumber
	}
	return 0
}

func (m *Result) GetArchived() string {
	if m != nil {
		return m.Archived
	}
	return ""
}

func (m *Result) GetDatecreated() string {
	if m != nil {
		return m.Datecreated
	}
	return ""
}

func (m *Result) GetDatemodefied() string {
	if m != nil {
		return m.Datemodefied
	}
	return ""
}

func (m *Result) GetFilesize() int32 {
	if m != nil {
		return m.Filesize
	}
	return 0
}

func (m *Result) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Result) GetImagefilename() string {
	if m != nil {
		return m.Imagefilename
	}
	return ""
}

func (m *Result) GetImagerotated() int32 {
	if m != nil {
		return m.Imagerotated
	}
	return 0
}

func (m *Result) GetThumbnailsize() int32 {
	if m != nil {
		return m.Thumbnailsize
	}
	return 0
}

func (m *Result) GetWebfilename() string {
	if m != nil {
		return m.Webfilename
	}
	return ""
}

func (m *Result) GetMimetype() string {
	if m != nil {
		return m.Mimetype
	}
	return ""
}

func (m *Result) GetInspiresponsedata() *InspiPutResponse {
	if m != nil {
		return m.Inspiresponsedata
	}
	return nil
}

func (m *Result) GetVendorwebresponsedata() *VendorWebPutResponse {
	if m != nil {
		return m.Vendorwebresponsedata
	}
	return nil
}

func (m *Result) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

type InspiPutResponse struct {
	Photodetailid int64 `protobuf:"varint,1,opt,name=photodetailid" json:"photodetailid,omitempty"`
}

func (m *InspiPutResponse) Reset()                    { *m = InspiPutResponse{} }
func (m *InspiPutResponse) String() string            { return proto.CompactTextString(m) }
func (*InspiPutResponse) ProtoMessage()               {}
func (*InspiPutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *InspiPutResponse) GetPhotodetailid() int64 {
	if m != nil {
		return m.Photodetailid
	}
	return 0
}

type VendorWebPutResponse struct {
	Documentid   int64 `protobuf:"varint,1,opt,name=documentid" json:"documentid,omitempty"`
	Annotationid int64 `protobuf:"varint,2,opt,name=annotationid" json:"annotationid,omitempty"`
}

func (m *VendorWebPutResponse) Reset()                    { *m = VendorWebPutResponse{} }
func (m *VendorWebPutResponse) String() string            { return proto.CompactTextString(m) }
func (*VendorWebPutResponse) ProtoMessage()               {}
func (*VendorWebPutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *VendorWebPutResponse) GetDocumentid() int64 {
	if m != nil {
		return m.Documentid
	}
	return 0
}

func (m *VendorWebPutResponse) GetAnnotationid() int64 {
	if m != nil {
		return m.Annotationid
	}
	return 0
}

// Message when Put request failed
type Error struct {
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Data    string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// Response from the Put call
type Response struct {
	Jsonrpc string  `protobuf:"bytes,1,opt,name=jsonrpc" json:"jsonrpc,omitempty"`
	Id      int32   `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Result  *Result `protobuf:"bytes,3,opt,name=result" json:"result,omitempty"`
	Error   *Error  `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Response) GetJsonrpc() string {
	if m != nil {
		return m.Jsonrpc
	}
	return ""
}

func (m *Response) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "contentservice.Params")
	proto.RegisterType((*Request)(nil), "contentservice.Request")
	proto.RegisterType((*Result)(nil), "contentservice.Result")
	proto.RegisterType((*InspiPutResponse)(nil), "contentservice.InspiPutResponse")
	proto.RegisterType((*VendorWebPutResponse)(nil), "contentservice.VendorWebPutResponse")
	proto.RegisterType((*Error)(nil), "contentservice.Error")
	proto.RegisterType((*Response)(nil), "contentservice.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ContentService service

type ContentServiceClient interface {
	// Makes a Put call
	Put(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type contentServiceClient struct {
	cc *grpc.ClientConn
}

func NewContentServiceClient(cc *grpc.ClientConn) ContentServiceClient {
	return &contentServiceClient{cc}
}

func (c *contentServiceClient) Put(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/contentservice.ContentService/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ContentService service

type ContentServiceServer interface {
	// Makes a Put call
	Put(context.Context, *Request) (*Response, error)
}

func RegisterContentServiceServer(s *grpc.Server, srv ContentServiceServer) {
	s.RegisterService(&_ContentService_serviceDesc, srv)
}

func _ContentService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contentservice.ContentService/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).Put(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "contentservice.ContentService",
	HandlerType: (*ContentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _ContentService_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contentservice.proto",
}

func init() { proto.RegisterFile("contentservice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 761 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x6e, 0xdb, 0x38,
	0x10, 0x5e, 0xdb, 0xb1, 0x6c, 0x8f, 0x13, 0x6f, 0xc2, 0xcd, 0x0f, 0x11, 0x2c, 0x02, 0x43, 0x08,
	0x16, 0x06, 0x16, 0xf0, 0x21, 0x7b, 0x59, 0xec, 0x75, 0xd1, 0x43, 0x80, 0xa2, 0x08, 0x54, 0xa0,
	0x05, 0x72, 0xa3, 0xc5, 0x89, 0xcd, 0xc2, 0x12, 0x55, 0x8a, 0xca, 0x4f, 0xdf, 0xa2, 0x2f, 0xd2,
	0x37, 0xe8, 0x9b, 0xf4, 0x61, 0x0a, 0x0e, 0x25, 0x45, 0x52, 0x9c, 0x53, 0x6f, 0x9a, 0x8f, 0x1f,
	0x67, 0x86, 0xdf, 0xfc, 0x08, 0x8e, 0x63, 0x9d, 0x5a, 0x4c, 0x6d, 0x8e, 0xe6, 0x5e, 0xc5, 0xb8,
	0xcc, 0x8c, 0xb6, 0x9a, 0xcd, 0xda, 0x68, 0xf8, 0xad, 0x0f, 0xc1, 0x8d, 0x30, 0x22, 0xc9, 0xd9,
	0x25, 0x1c, 0xb8, 0x43, 0x23, 0x62, 0x6b, 0xb5, 0x51, 0x92, 0xf7, 0xe6, 0xbd, 0xc5, 0x20, 0x6a,
	0x83, 0x6c, 0x0e, 0x53, 0x6d, 0x24, 0x9a, 0xb4, 0x48, 0x56, 0x68, 0x78, 0x9f, 0x38, 0x4d, 0x88,
	0xfd, 0x09, 0x13, 0x95, 0x88, 0x35, 0xda, 0xa7, 0x0c, 0xf9, 0x60, 0xde, 0x5b, 0x0c, 0xa3, 0x67,
	0x80, 0x9d, 0xc3, 0xf8, 0x4e, 0x6d, 0x31, 0x15, 0x09, 0xf2, 0xbd, 0x79, 0x6f, 0x31, 0x89, 0x6a,
	0x9b, 0x5d, 0x00, 0x10, 0xf1, 0x41, 0x49, 0xbb, 0xe1, 0x43, 0xba, 0xda, 0x40, 0x5c, 0x6c, 0xb2,
	0x36, 0xa8, 0xd6, 0x1b, 0xcb, 0x03, 0x22, 0x34, 0x21, 0xc7, 0x30, 0xb8, 0x45, 0x91, 0xa3, 0x14,
	0x16, 0xf9, 0x88, 0x02, 0x34, 0x21, 0x17, 0x5f, 0x62, 0x66, 0x63, 0x2d, 0x91, 0x8f, 0x7d, 0xfc,
	0xca, 0x66, 0x21, 0xec, 0xbb, 0x5c, 0x2a, 0x89, 0xf8, 0x64, 0xde, 0x5b, 0xec, 0x47, 0x2d, 0x2c,
	0xfc, 0xde, 0x83, 0x51, 0x84, 0x9f, 0x0b, 0xcc, 0x2d, 0xe3, 0x30, 0xfa, 0x94, 0xeb, 0xd4, 0x64,
	0x31, 0x69, 0x35, 0x89, 0x2a, 0x93, 0x9d, 0x42, 0x90, 0xa0, 0xdd, 0x68, 0x49, 0x02, 0x4d, 0xa2,
	0xd2, 0x62, 0x4b, 0x08, 0x32, 0x52, 0x9b, 0x84, 0x99, 0x5e, 0x9d, 0x2e, 0x3b, 0x55, 0xf2, 0xb5,
	0x88, 0x4a, 0x16, 0x9b, 0x41, 0x5f, 0x49, 0xd2, 0x69, 0x18, 0xf5, 0x95, 0x64, 0x7f, 0xc1, 0x4c,
	0xe4, 0x4f, 0x69, 0x9c, 0x60, 0x9e, 0x8b, 0x35, 0x2a, 0x59, 0xaa, 0xd4, 0x41, 0x5d, 0x66, 0xae,
	0x66, 0x8e, 0xe0, 0x55, 0xaa, 0xcc, 0xf0, 0x47, 0x00, 0x41, 0x84, 0x79, 0xb1, 0xb5, 0xee, 0xb9,
	0x55, 0x6d, 0xeb, 0x7a, 0x0f, 0xa3, 0x16, 0xd6, 0x15, 0xb4, 0xbf, 0x53, 0xd0, 0x3c, 0x16, 0x29,
	0x1d, 0x0f, 0xbc, 0xa0, 0x95, 0xdd, 0x6e, 0x85, 0xbd, 0x6e, 0x2b, 0xfc, 0x7a, 0xb9, 0x9b, 0xc5,
	0x1c, 0x75, 0x8a, 0x79, 0x01, 0x20, 0x31, 0x8f, 0x33, 0x83, 0x77, 0xea, 0xb1, 0x2c, 0x75, 0x03,
	0xf1, 0x77, 0xf3, 0xd8, 0xe2, 0xa3, 0xa5, 0x42, 0xd3, 0x5d, 0x6f, 0xbb, 0xb3, 0x58, 0x58, 0x5c,
	0x6b, 0xf3, 0xc4, 0xc1, 0x9f, 0x55, 0x76, 0x77, 0x00, 0xa6, 0x2f, 0x07, 0xe0, 0x1c, 0xc6, 0xc2,
	0xc4, 0x1b, 0x75, 0x8f, 0x92, 0xef, 0xfb, 0xdb, 0x95, 0xed, 0x6e, 0x3b, 0x65, 0x62, 0x83, 0xc2,
	0xa2, 0xe4, 0x07, 0x5e, 0xcf, 0x06, 0xe4, 0xaa, 0xe2, 0xcc, 0x44, 0x4b, 0xbc, 0x53, 0x28, 0xf9,
	0x8c, 0x28, 0x2d, 0xac, 0x1a, 0xa2, 0x5c, 0x7d, 0x41, 0xfe, 0x3b, 0xc9, 0x52, 0xdb, 0x65, 0xcb,
	0x1c, 0xd6, 0x2d, 0x73, 0x09, 0x07, 0x24, 0x59, 0x3d, 0x75, 0x47, 0xe4, 0xb0, 0x0d, 0xba, 0xa8,
	0x04, 0x18, 0x6d, 0x29, 0x31, 0xe6, 0x7b, 0xa1, 0x89, 0x39, 0x4f, 0x76, 0x53, 0x24, 0xab, 0x54,
	0xa8, 0x2d, 0x85, 0xfe, 0x83, 0x48, 0x6d, 0xd0, 0xbd, 0xf0, 0x01, 0x57, 0x75, 0xb4, 0x63, 0xff,
	0xc2, 0x06, 0xe4, 0xb2, 0x4f, 0x54, 0xe2, 0x9b, 0xe2, 0xc4, 0xeb, 0x53, 0xd9, 0xec, 0x1d, 0x1c,
	0xa9, 0x34, 0xcf, 0x94, 0xc1, 0x3c, 0xd3, 0x29, 0xb5, 0x98, 0xe0, 0xa7, 0x34, 0x2b, 0xf3, 0xee,
	0xac, 0x5c, 0x3b, 0xe2, 0x4d, 0x61, 0xa3, 0x92, 0x1b, 0xbd, 0xbc, 0xca, 0x6e, 0xe1, 0xe4, 0x1e,
	0x53, 0xa9, 0xcd, 0x03, 0xae, 0x5a, 0x3e, 0xcf, 0xc8, 0xe7, 0x65, 0xd7, 0xe7, 0x07, 0x22, 0x7f,
	0xc4, 0x55, 0xd3, 0xef, 0x6e, 0x17, 0x8c, 0xc1, 0xde, 0xba, 0x50, 0x92, 0x73, 0x7a, 0x03, 0x7d,
	0x87, 0xff, 0xc2, 0x61, 0x37, 0x2d, 0xa7, 0x5b, 0xb6, 0xd1, 0x56, 0x4b, 0xb4, 0x42, 0x6d, 0x9f,
	0x17, 0x6b, 0x0b, 0x0c, 0x6f, 0xe1, 0x78, 0x57, 0x70, 0xea, 0x63, 0x1d, 0x17, 0x09, 0xa6, 0xb6,
	0xbe, 0xda, 0x40, 0x5c, 0xe5, 0x44, 0x9a, 0xba, 0x12, 0x29, 0x9d, 0x2a, 0x59, 0x6e, 0xe4, 0x16,
	0x16, 0x5e, 0xc3, 0xf0, 0x8d, 0x31, 0xda, 0xb8, 0x94, 0x69, 0x58, 0xfc, 0xa8, 0xd3, 0xb7, 0xdb,
	0x15, 0xe5, 0xe2, 0x28, 0xc7, 0xbb, 0x32, 0x1d, 0x9b, 0xb4, 0xf2, 0x63, 0x4d, 0xdf, 0xe1, 0xd7,
	0x1e, 0x8c, 0xeb, 0xdc, 0x5e, 0x5f, 0x80, 0xbe, 0x0b, 0xfb, 0x75, 0x17, 0x2e, 0x21, 0x30, 0xb4,
	0x75, 0x5e, 0x5b, 0x7c, 0x7e, 0x27, 0x45, 0x25, 0x8b, 0xfd, 0x0d, 0x43, 0x74, 0x19, 0xd3, 0xd6,
	0x98, 0x5e, 0x9d, 0x74, 0xe9, 0xf4, 0x9c, 0xc8, 0x73, 0xae, 0xde, 0xc2, 0xec, 0x7f, 0x7f, 0xfc,
	0xde, 0x1f, 0xb3, 0xff, 0x60, 0x70, 0x53, 0x58, 0x76, 0xf6, 0x32, 0x0a, 0x6d, 0xee, 0x73, 0xbe,
	0x23, 0x3c, 0x3d, 0x29, 0xfc, 0x6d, 0x15, 0xd0, 0x9f, 0xf2, 0x9f, 0x9f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x00, 0x2d, 0xa8, 0x45, 0x41, 0x07, 0x00, 0x00,
}
