// Code generated by protoc-gen-go.
// source: contentservice.proto
// DO NOT EDIT!

/*
Package contentservice is a generated protocol buffer package.

It is generated from these files:
	contentservice.proto

It has these top-level messages:
	PutRequest
	JSONRPCRequest
	PutResponse
	InspiPutResponse
	VendorWebPutResponse
	JSONRPCError
	JSONRPCResponse
*/
package contentservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Request sent to the server
type PutRequest struct {
	Contractorid int64  `protobuf:"varint,1,opt,name=contractorid" json:"contractorid,omitempty"`
	Ordernumber  int64  `protobuf:"varint,2,opt,name=ordernumber" json:"ordernumber,omitempty"`
	Imagetype    int32  `protobuf:"varint,3,opt,name=imagetype" json:"imagetype,omitempty"`
	Filename     string `protobuf:"bytes,4,opt,name=filename" json:"filename,omitempty"`
	Imagewidth   int32  `protobuf:"varint,5,opt,name=imagewidth" json:"imagewidth,omitempty"`
	Imageheight  int32  `protobuf:"varint,6,opt,name=imageheight" json:"imageheight,omitempty"`
	Releasedate  string `protobuf:"bytes,7,opt,name=releasedate" json:"releasedate,omitempty"`
	Deptcode     string `protobuf:"bytes,8,opt,name=deptcode" json:"deptcode,omitempty"`
	Filecontents []byte `protobuf:"bytes,9,opt,name=filecontents,proto3" json:"filecontents,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PutRequest) GetContractorid() int64 {
	if m != nil {
		return m.Contractorid
	}
	return 0
}

func (m *PutRequest) GetOrdernumber() int64 {
	if m != nil {
		return m.Ordernumber
	}
	return 0
}

func (m *PutRequest) GetImagetype() int32 {
	if m != nil {
		return m.Imagetype
	}
	return 0
}

func (m *PutRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *PutRequest) GetImagewidth() int32 {
	if m != nil {
		return m.Imagewidth
	}
	return 0
}

func (m *PutRequest) GetImageheight() int32 {
	if m != nil {
		return m.Imageheight
	}
	return 0
}

func (m *PutRequest) GetReleasedate() string {
	if m != nil {
		return m.Releasedate
	}
	return ""
}

func (m *PutRequest) GetDeptcode() string {
	if m != nil {
		return m.Deptcode
	}
	return ""
}

func (m *PutRequest) GetFilecontents() []byte {
	if m != nil {
		return m.Filecontents
	}
	return nil
}

// Request sent to the servicebus Put call
type JSONRPCRequest struct {
	Jsonrpc        string      `protobuf:"bytes,1,opt,name=jsonrpc" json:"jsonrpc,omitempty"`
	Method         string      `protobuf:"bytes,2,opt,name=method" json:"method,omitempty"`
	Params         *PutRequest `protobuf:"bytes,3,opt,name=params" json:"params,omitempty"`
	Id             int32       `protobuf:"varint,4,opt,name=id" json:"id,omitempty"`
	Asyncmessageid int32       `protobuf:"varint,5,opt,name=asyncmessageid" json:"asyncmessageid,omitempty"`
	Traceid        int32       `protobuf:"varint,6,opt,name=traceid" json:"traceid,omitempty"`
}

func (m *JSONRPCRequest) Reset()                    { *m = JSONRPCRequest{} }
func (m *JSONRPCRequest) String() string            { return proto.CompactTextString(m) }
func (*JSONRPCRequest) ProtoMessage()               {}
func (*JSONRPCRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *JSONRPCRequest) GetJsonrpc() string {
	if m != nil {
		return m.Jsonrpc
	}
	return ""
}

func (m *JSONRPCRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *JSONRPCRequest) GetParams() *PutRequest {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *JSONRPCRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *JSONRPCRequest) GetAsyncmessageid() int32 {
	if m != nil {
		return m.Asyncmessageid
	}
	return 0
}

func (m *JSONRPCRequest) GetTraceid() int32 {
	if m != nil {
		return m.Traceid
	}
	return 0
}

// Response from the Server
type PutResponse struct {
	Contractorid          int32                 `protobuf:"varint,1,opt,name=contractorid" json:"contractorid,omitempty"`
	Releasedate           string                `protobuf:"bytes,2,opt,name=releasedate" json:"releasedate,omitempty"`
	Scandate              string                `protobuf:"bytes,3,opt,name=scandate" json:"scandate,omitempty"`
	Imagetype             int32                 `protobuf:"varint,4,opt,name=imagetype" json:"imagetype,omitempty"`
	Imagewidth            int32                 `protobuf:"varint,5,opt,name=imagewidth" json:"imagewidth,omitempty"`
	Imageheight           int32                 `protobuf:"varint,6,opt,name=imageheight" json:"imageheight,omitempty"`
	Deptcode              string                `protobuf:"bytes,7,opt,name=deptcode" json:"deptcode,omitempty"`
	Descprefix            string                `protobuf:"bytes,8,opt,name=descprefix" json:"descprefix,omitempty"`
	Desctext              string                `protobuf:"bytes,9,opt,name=desctext" json:"desctext,omitempty"`
	Category              string                `protobuf:"bytes,10,opt,name=category" json:"category,omitempty"`
	Ordernumber           int64                 `protobuf:"varint,11,opt,name=ordernumber" json:"ordernumber,omitempty"`
	Archived              string                `protobuf:"bytes,12,opt,name=archived" json:"archived,omitempty"`
	Datecreated           string                `protobuf:"bytes,13,opt,name=datecreated" json:"datecreated,omitempty"`
	Datemodefied          string                `protobuf:"bytes,14,opt,name=datemodefied" json:"datemodefied,omitempty"`
	Filesize              int32                 `protobuf:"varint,15,opt,name=filesize" json:"filesize,omitempty"`
	Id                    int32                 `protobuf:"varint,16,opt,name=id" json:"id,omitempty"`
	Imagefilename         string                `protobuf:"bytes,17,opt,name=imagefilename" json:"imagefilename,omitempty"`
	Imagerotated          int32                 `protobuf:"varint,18,opt,name=imagerotated" json:"imagerotated,omitempty"`
	Thumbnailsize         int32                 `protobuf:"varint,19,opt,name=thumbnailsize" json:"thumbnailsize,omitempty"`
	Webfilename           string                `protobuf:"bytes,20,opt,name=webfilename" json:"webfilename,omitempty"`
	Mimetype              string                `protobuf:"bytes,21,opt,name=mimetype" json:"mimetype,omitempty"`
	Inspiresponsedata     *InspiPutResponse     `protobuf:"bytes,22,opt,name=inspiresponsedata" json:"inspiresponsedata,omitempty"`
	Vendorwebresponsedata *VendorWebPutResponse `protobuf:"bytes,23,opt,name=vendorwebresponsedata" json:"vendorwebresponsedata,omitempty"`
	Guid                  string                `protobuf:"bytes,24,opt,name=guid" json:"guid,omitempty"`
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PutResponse) GetContractorid() int32 {
	if m != nil {
		return m.Contractorid
	}
	return 0
}

func (m *PutResponse) GetReleasedate() string {
	if m != nil {
		return m.Releasedate
	}
	return ""
}

func (m *PutResponse) GetScandate() string {
	if m != nil {
		return m.Scandate
	}
	return ""
}

func (m *PutResponse) GetImagetype() int32 {
	if m != nil {
		return m.Imagetype
	}
	return 0
}

func (m *PutResponse) GetImagewidth() int32 {
	if m != nil {
		return m.Imagewidth
	}
	return 0
}

func (m *PutResponse) GetImageheight() int32 {
	if m != nil {
		return m.Imageheight
	}
	return 0
}

func (m *PutResponse) GetDeptcode() string {
	if m != nil {
		return m.Deptcode
	}
	return ""
}

func (m *PutResponse) GetDescprefix() string {
	if m != nil {
		return m.Descprefix
	}
	return ""
}

func (m *PutResponse) GetDesctext() string {
	if m != nil {
		return m.Desctext
	}
	return ""
}

func (m *PutResponse) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *PutResponse) GetOrdernumber() int64 {
	if m != nil {
		return m.Ordernumber
	}
	return 0
}

func (m *PutResponse) GetArchived() string {
	if m != nil {
		return m.Archived
	}
	return ""
}

func (m *PutResponse) GetDatecreated() string {
	if m != nil {
		return m.Datecreated
	}
	return ""
}

func (m *PutResponse) GetDatemodefied() string {
	if m != nil {
		return m.Datemodefied
	}
	return ""
}

func (m *PutResponse) GetFilesize() int32 {
	if m != nil {
		return m.Filesize
	}
	return 0
}

func (m *PutResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PutResponse) GetImagefilename() string {
	if m != nil {
		return m.Imagefilename
	}
	return ""
}

func (m *PutResponse) GetImagerotated() int32 {
	if m != nil {
		return m.Imagerotated
	}
	return 0
}

func (m *PutResponse) GetThumbnailsize() int32 {
	if m != nil {
		return m.Thumbnailsize
	}
	return 0
}

func (m *PutResponse) GetWebfilename() string {
	if m != nil {
		return m.Webfilename
	}
	return ""
}

func (m *PutResponse) GetMimetype() string {
	if m != nil {
		return m.Mimetype
	}
	return ""
}

func (m *PutResponse) GetInspiresponsedata() *InspiPutResponse {
	if m != nil {
		return m.Inspiresponsedata
	}
	return nil
}

func (m *PutResponse) GetVendorwebresponsedata() *VendorWebPutResponse {
	if m != nil {
		return m.Vendorwebresponsedata
	}
	return nil
}

func (m *PutResponse) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

type InspiPutResponse struct {
	Photodetailid int64 `protobuf:"varint,1,opt,name=photodetailid" json:"photodetailid,omitempty"`
}

func (m *InspiPutResponse) Reset()                    { *m = InspiPutResponse{} }
func (m *InspiPutResponse) String() string            { return proto.CompactTextString(m) }
func (*InspiPutResponse) ProtoMessage()               {}
func (*InspiPutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *InspiPutResponse) GetPhotodetailid() int64 {
	if m != nil {
		return m.Photodetailid
	}
	return 0
}

type VendorWebPutResponse struct {
	Documentid   int64 `protobuf:"varint,1,opt,name=documentid" json:"documentid,omitempty"`
	Annotationid int64 `protobuf:"varint,2,opt,name=annotationid" json:"annotationid,omitempty"`
}

func (m *VendorWebPutResponse) Reset()                    { *m = VendorWebPutResponse{} }
func (m *VendorWebPutResponse) String() string            { return proto.CompactTextString(m) }
func (*VendorWebPutResponse) ProtoMessage()               {}
func (*VendorWebPutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *VendorWebPutResponse) GetDocumentid() int64 {
	if m != nil {
		return m.Documentid
	}
	return 0
}

func (m *VendorWebPutResponse) GetAnnotationid() int64 {
	if m != nil {
		return m.Annotationid
	}
	return 0
}

// Message when Put request failed
type JSONRPCError struct {
	Code    int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Data    string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *JSONRPCError) Reset()                    { *m = JSONRPCError{} }
func (m *JSONRPCError) String() string            { return proto.CompactTextString(m) }
func (*JSONRPCError) ProtoMessage()               {}
func (*JSONRPCError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *JSONRPCError) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *JSONRPCError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *JSONRPCError) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// Response from the servicebus Put call
type JSONRPCResponse struct {
	Jsonrpc string        `protobuf:"bytes,1,opt,name=jsonrpc" json:"jsonrpc,omitempty"`
	Id      int32         `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Result  *PutResponse  `protobuf:"bytes,3,opt,name=result" json:"result,omitempty"`
	Error   *JSONRPCError `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
}

func (m *JSONRPCResponse) Reset()                    { *m = JSONRPCResponse{} }
func (m *JSONRPCResponse) String() string            { return proto.CompactTextString(m) }
func (*JSONRPCResponse) ProtoMessage()               {}
func (*JSONRPCResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *JSONRPCResponse) GetJsonrpc() string {
	if m != nil {
		return m.Jsonrpc
	}
	return ""
}

func (m *JSONRPCResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *JSONRPCResponse) GetResult() *PutResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *JSONRPCResponse) GetError() *JSONRPCError {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*PutRequest)(nil), "contentservice.PutRequest")
	proto.RegisterType((*JSONRPCRequest)(nil), "contentservice.JSONRPCRequest")
	proto.RegisterType((*PutResponse)(nil), "contentservice.PutResponse")
	proto.RegisterType((*InspiPutResponse)(nil), "contentservice.InspiPutResponse")
	proto.RegisterType((*VendorWebPutResponse)(nil), "contentservice.VendorWebPutResponse")
	proto.RegisterType((*JSONRPCError)(nil), "contentservice.JSONRPCError")
	proto.RegisterType((*JSONRPCResponse)(nil), "contentservice.JSONRPCResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ContentService service

type ContentServiceClient interface {
	// Makes a Put call
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
}

type contentServiceClient struct {
	cc *grpc.ClientConn
}

func NewContentServiceClient(cc *grpc.ClientConn) ContentServiceClient {
	return &contentServiceClient{cc}
}

func (c *contentServiceClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := grpc.Invoke(ctx, "/contentservice.ContentService/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ContentService service

type ContentServiceServer interface {
	// Makes a Put call
	Put(context.Context, *PutRequest) (*PutResponse, error)
}

func RegisterContentServiceServer(s *grpc.Server, srv ContentServiceServer) {
	s.RegisterService(&_ContentService_serviceDesc, srv)
}

func _ContentService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contentservice.ContentService/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "contentservice.ContentService",
	HandlerType: (*ContentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _ContentService_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contentservice.proto",
}

func init() { proto.RegisterFile("contentservice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 764 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x6e, 0xe3, 0x36,
	0x10, 0xae, 0xed, 0xd8, 0x89, 0xc7, 0x5e, 0xef, 0x2e, 0x9b, 0xdd, 0x12, 0x6e, 0x10, 0x18, 0x42,
	0x50, 0xf8, 0x94, 0x83, 0x73, 0xe9, 0xb1, 0x40, 0xd0, 0x43, 0x7b, 0x48, 0x0d, 0x05, 0x68, 0x81,
	0xdc, 0x68, 0x71, 0x62, 0xb3, 0xb0, 0x44, 0x95, 0xa4, 0xf2, 0xd3, 0xe7, 0xe9, 0x03, 0xf4, 0x31,
	0xfa, 0x1a, 0x7d, 0x93, 0x82, 0x43, 0x49, 0x91, 0x14, 0x37, 0x97, 0xbd, 0x79, 0x3e, 0x7d, 0xf3,
	0xc3, 0x6f, 0x7e, 0x0c, 0xa7, 0x89, 0xce, 0x1c, 0x66, 0xce, 0xa2, 0x79, 0x50, 0x09, 0x5e, 0xe6,
	0x46, 0x3b, 0xcd, 0x66, 0x6d, 0x34, 0xfa, 0xbb, 0x0f, 0xb0, 0x2e, 0x5c, 0x8c, 0x7f, 0x14, 0x68,
	0x1d, 0x8b, 0x60, 0xea, 0x09, 0x46, 0x24, 0x4e, 0x1b, 0x25, 0x79, 0x6f, 0xd1, 0x5b, 0x0e, 0xe2,
	0x16, 0xc6, 0x16, 0x30, 0xd1, 0x46, 0xa2, 0xc9, 0x8a, 0x74, 0x83, 0x86, 0xf7, 0x89, 0xd2, 0x84,
	0xd8, 0x19, 0x8c, 0x55, 0x2a, 0xb6, 0xe8, 0x9e, 0x73, 0xe4, 0x83, 0x45, 0x6f, 0x39, 0x8c, 0x5f,
	0x00, 0x36, 0x87, 0x93, 0x7b, 0xb5, 0xc7, 0x4c, 0xa4, 0xc8, 0x8f, 0x16, 0xbd, 0xe5, 0x38, 0xae,
	0x6d, 0x76, 0x0e, 0x40, 0xc4, 0x47, 0x25, 0xdd, 0x8e, 0x0f, 0xc9, 0xb5, 0x81, 0xf8, 0xdc, 0x64,
	0xed, 0x50, 0x6d, 0x77, 0x8e, 0x8f, 0x88, 0xd0, 0x84, 0x3c, 0xc3, 0xe0, 0x1e, 0x85, 0x45, 0x29,
	0x1c, 0xf2, 0x63, 0x4a, 0xd0, 0x84, 0x7c, 0x7e, 0x89, 0xb9, 0x4b, 0xb4, 0x44, 0x7e, 0x12, 0xf2,
	0x57, 0xb6, 0x7f, 0xbf, 0xaf, 0xa5, 0x12, 0x89, 0x8f, 0x17, 0xbd, 0xe5, 0x34, 0x6e, 0x61, 0xd1,
	0x3f, 0x3d, 0x98, 0xfd, 0x7c, 0xfb, 0xcb, 0x4d, 0xbc, 0xbe, 0xae, 0x64, 0xe3, 0x70, 0xfc, 0xbb,
	0xd5, 0x99, 0xc9, 0x13, 0x52, 0x6c, 0x1c, 0x57, 0x26, 0xfb, 0x0c, 0xa3, 0x14, 0xdd, 0x4e, 0x4b,
	0xd2, 0x69, 0x1c, 0x97, 0x16, 0x5b, 0xc1, 0x28, 0x17, 0x46, 0xa4, 0x96, 0xf4, 0x99, 0xac, 0xe6,
	0x97, 0x9d, 0x76, 0xbd, 0x34, 0x25, 0x2e, 0x99, 0x6c, 0x06, 0x7d, 0x25, 0x49, 0xb2, 0x61, 0xdc,
	0x57, 0x92, 0x7d, 0x07, 0x33, 0x61, 0x9f, 0xb3, 0x24, 0x45, 0x6b, 0xc5, 0x16, 0x95, 0x2c, 0x05,
	0xeb, 0xa0, 0xbe, 0x3a, 0xdf, 0x3d, 0x4f, 0x08, 0x82, 0x55, 0x66, 0xf4, 0xef, 0x08, 0x26, 0x94,
	0xc8, 0xe6, 0x3a, 0xb3, 0x78, 0xb0, 0xfd, 0xc3, 0xd7, 0xed, 0x6f, 0x0a, 0xdc, 0x3f, 0x28, 0xb0,
	0x4d, 0x44, 0x46, 0x9f, 0x07, 0x41, 0xe0, 0xca, 0x6e, 0x8f, 0xc6, 0x51, 0x77, 0x34, 0xbe, 0xbc,
	0xfd, 0xcd, 0xe6, 0x1e, 0x77, 0x9a, 0x7b, 0x0e, 0x20, 0xd1, 0x26, 0xb9, 0xc1, 0x7b, 0xf5, 0x54,
	0xb6, 0xbe, 0x81, 0x04, 0x5f, 0x9b, 0x38, 0x7c, 0x72, 0xd4, 0x78, 0xf2, 0x0d, 0xb6, 0xff, 0x96,
	0x08, 0x87, 0x5b, 0x6d, 0x9e, 0x39, 0x84, 0x6f, 0x95, 0xdd, 0x5d, 0x88, 0xc9, 0xeb, 0x85, 0x98,
	0xc3, 0x89, 0x30, 0xc9, 0x4e, 0x3d, 0xa0, 0xe4, 0xd3, 0xe0, 0x5d, 0xd9, 0xde, 0xdb, 0x2b, 0x93,
	0x18, 0x14, 0x0e, 0x25, 0x7f, 0x17, 0xf4, 0x6c, 0x40, 0xbe, 0x2b, 0xde, 0x4c, 0xb5, 0xc4, 0x7b,
	0x85, 0x92, 0xcf, 0x88, 0xd2, 0xc2, 0xaa, 0xa5, 0xb2, 0xea, 0x4f, 0xe4, 0xef, 0x49, 0x96, 0xda,
	0x2e, 0xe7, 0xe6, 0x43, 0x3d, 0x37, 0x17, 0xf0, 0x8e, 0x24, 0xab, 0xb7, 0xf0, 0x23, 0x05, 0x6c,
	0x83, 0x3e, 0x2b, 0x01, 0x46, 0x3b, 0x2a, 0x8c, 0x85, 0x59, 0x68, 0x62, 0x3e, 0x92, 0xdb, 0x15,
	0xe9, 0x26, 0x13, 0x6a, 0x4f, 0xa9, 0xbf, 0x26, 0x52, 0x1b, 0xf4, 0x2f, 0x7c, 0xc4, 0x4d, 0x9d,
	0xed, 0x34, 0xbc, 0xb0, 0x01, 0xf9, 0xea, 0x53, 0x95, 0x86, 0xa1, 0xf8, 0x14, 0xf4, 0xa9, 0x6c,
	0x76, 0x03, 0x1f, 0x55, 0x66, 0x73, 0x65, 0xca, 0x21, 0x95, 0xc2, 0x09, 0xfe, 0x99, 0x96, 0x66,
	0xd1, 0x5d, 0x9a, 0x9f, 0x3c, 0xb1, 0x31, 0xd0, 0xf1, 0x6b, 0x57, 0x76, 0x07, 0x9f, 0x1e, 0x30,
	0x93, 0xda, 0x3c, 0xe2, 0xa6, 0x15, 0xf3, 0x1b, 0x8a, 0x79, 0xd1, 0x8d, 0xf9, 0x2b, 0x91, 0x7f,
	0xc3, 0x4d, 0x33, 0xee, 0xe1, 0x10, 0x8c, 0xc1, 0xd1, 0xb6, 0x50, 0x92, 0x73, 0x7a, 0x03, 0xfd,
	0x8e, 0xbe, 0x87, 0x0f, 0xdd, 0xb2, 0xbc, 0x6e, 0xf9, 0x4e, 0x3b, 0x2d, 0xd1, 0x09, 0xb5, 0xaf,
	0xef, 0x6c, 0x1b, 0x8c, 0xee, 0xe0, 0xf4, 0x50, 0x72, 0x9a, 0x63, 0x9d, 0x14, 0x29, 0x66, 0xae,
	0x76, 0x6d, 0x20, 0xbe, 0x73, 0x22, 0xcb, 0x7c, 0x8b, 0x94, 0xce, 0x94, 0x2c, 0x2f, 0x74, 0x0b,
	0x8b, 0xd6, 0x30, 0x2d, 0x6f, 0xd8, 0x8f, 0xc6, 0x68, 0xe3, 0x2b, 0xa7, 0x9d, 0x09, 0x1b, 0x4f,
	0xbf, 0xfd, 0xdd, 0x28, 0x8f, 0x48, 0xb9, 0xe5, 0x95, 0xe9, 0xd9, 0x24, 0x59, 0xd8, 0x6e, 0xfa,
	0x1d, 0xfd, 0xd5, 0x83, 0xf7, 0xf5, 0x59, 0x2c, 0x2b, 0xfd, 0xff, 0xbb, 0x18, 0x66, 0xb2, 0x5f,
	0xcf, 0xe4, 0x15, 0x8c, 0x0c, 0xda, 0x62, 0xef, 0xca, 0x7b, 0xf8, 0xed, 0xc1, 0x7b, 0x58, 0xaa,
	0x5f, 0x52, 0xd9, 0x0a, 0x86, 0xe8, 0xab, 0xa7, 0x43, 0x32, 0x59, 0x9d, 0x75, 0x7d, 0x9a, 0x2f,
	0x8c, 0x03, 0x75, 0x15, 0xc3, 0xec, 0x3a, 0xb0, 0x6e, 0x03, 0x8b, 0xfd, 0x00, 0x83, 0x75, 0xe1,
	0xd8, 0x1b, 0x17, 0x78, 0xfe, 0x56, 0x35, 0xd1, 0x57, 0x9b, 0x11, 0xfd, 0xb7, 0x5e, 0xfd, 0x17,
	0x00, 0x00, 0xff, 0xff, 0xd4, 0x93, 0xa9, 0xb7, 0x73, 0x07, 0x00, 0x00,
}
